### ISSUE TITLE
Astyle check now fails "process exited with code 4" 

### ISSUE THREAD

**Issue by SpenceKonde** [per1234/artistic-style-action#5]
It looks like the URL it's trying to download astyle from may not be valid any more. Following search results gives me https://sourceforge.net/projects/astyle/files/astyle/astyle%203.1/astyle_3.1_linux.tar.gz/download, not while this action is trying to get it from https://iweb.dl.sourceforge.net/project/astyle/astyle/astyle%203.1/$ASTYLE_DOWNLOAD_FILENAME - so presumably we should be asking for https://sourceforge.net/projects/astyle/files/astyle/astyle%203.1/$ASTYLE_DOWNLOAD_FILENAME/download - I'm uncertain whether my diagnosis is correct, though.

**Comment by per1234** [comment]
Thanks for the report @SpenceKonde!

It should be fixed by https://github.com/per1234/artistic-style-action/commit/52ee102a20d019934eadb76e9c859552a1741ec6

It does look like your suggestion to use that "download" URL would work through a redirect. However, I decided to stick with the more minimal change for now since the previous URL did last quite some time. If there are more problems I'll switch to that approach.

I have already made a 1.0.2 release so any workflow using an action reference like `per1234/artistic-style-action@v1` will automatically use the version of the action with the fix the next time it runs.

Please let me know if you encounter any other problems.
Regards, Per
